version: '3'
services:
  web:
    image: nginx:1.16.0-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      - sh.acme.autoload.domain=gggitpl.com
    volumes:
      - /root/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/docker/nginx/mime.types:/etc/nginx/mime.types
      - /root/docker/nginx/conf.d:/etc/nginx/conf.d
      - /root/docker/nginx/html:/usr/share/nginx/html
      - /root/docker/nginx/log:/var/log/nginx
      - /root/docker/nginx/h5bp:/etc/nginx/h5bp
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh    
    command: daemon
    volumes:
      - /root/docker/nginx/acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock 
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone