version: "3"

services:
  gogs:
    image: gogs/gogs
    container_name: gogs
    ports:
      - "25822:22"
      - "25830:3000"
    volumes:
      - ./data:/data
    networks:
      - gogs
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=8WR7fWJrRK7cvQ
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=PQGLswcU8fbByeW
      - MYSQL_DATABASE=gogs
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - gogs
    restart: always

networks:
 gogs:
